load("@io_bazel_rules_docker//go:image.bzl", "go_image")
# load("@io_bazel_rules_go//go:def.bzl", "go_binary")

# go_binary(
#     name = "hello",
#     srcs = ["src/main.go"],
# )

go_image(
    name = "hello",
    srcs = ["src/main.go"],
)
